- name: Add Apt Keys
  become: yes
  apt_key:
    keyserver: "{{ item.key_server }}"
    id: "{{ item.id }}"
  with_items: "{{ apt_keys }}"

- name: Add Apt Repos
  become: yes
  apt_repository:
    state: present
    repo: "{{ item }}"
  with_items: "{{ apt_repos }}"

- name: Install APT Packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ apt_packages }}"
