# Tasks are run on local machine
- hosts: localhost
  become: true
  gather_facts: true
  pre_tasks:
    - name: Check Ansible Version
      assert:
        that: '(ansible_version.major, ansible_version.minor, ansible_version.revision) >= (2, 4, 0)'
        msg: 'Please install the recommended version 2.4+. You have Ansible {{ ansible_version.string }}.'
      run_once: yes
  roles:
     - { role: ubuntu, when: ansible_distribution == 'Ubuntu' }
     - { role: archlinux, when: ansible_distribution == 'Arch Linux' }
