- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    vagrant_version: 2.0.4
  pre_tasks:
    - name: Check Ansible Version
      assert:
        that: '(ansible_version.major, ansible_version.minor, ansible_version.revision) >= (2, 4, 0)'
        msg: 'Please install the recommended version 2.4+. You have Ansible {{ ansible_version.string }}.'
      run_once: yes

    - name: get the username running the deploy
      local_action: command whoami
      register: username_on_the_host

  roles:
     - { role: ubuntu, when: ansible_distribution == 'Ubuntu' }
     - { role: cmprescott.chrome, when: ansible_distribution == 'Ubuntu', become: true }
     - { role: ansible-role-vagrant }
     - role: gantsign.visual-studio-code
       users:
        - username: alois
          visual_studio_code_extensions:
            - PeterJausovec.vscode-docker
            - lukehoban.Go
            - dbaeumer.vscode-eslint
            - xabikos.JavaScriptSnippets
            - redhat.vscode-yaml
            - robertohuertasm.vscode-icons
          visual_studio_code_settings: {
            "files.associations": {
              "Vagrantfile": "ruby"
            },
	    "workbench.iconTheme": "vscode-icons",
	    "editor.tabSize": 2
          }
     - role: gantsign.oh-my-zsh
       # Default theme
       oh_my_zsh_theme: mh

       # Default plugins
       oh_my_zsh_plugins:
         - git

       # User configuration
       # Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
       users:
         - username: "{{ username_on_the_host.stdout }}"

     - { role: wtanaka.slack, become: true }

  tasks:

    - shell: which zsh
      register: zsh

    - name: set the shell to zsh
      become: true
      user:
        name: "{{ username_on_the_host.stdout }}"
        shell: "{{ zsh.stdout }}"

    - name: install zsh-syntax-highlighting
      shell: cd ~/.oh-my-zsh && git clone git://github.com/zsh-users/zsh-syntax-highlighting.git  
      args:
        creates: ~/.oh-my-zsh/zsh-syntax-highlighting

    - name: enable zsh-syntax-highlighting
      lineinfile:
        path: ~/.zshrc
        line: source ~/.oh-my-zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh  

    - name: install nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

    - name: Create a 2048-bit SSH
      user:
        name: "{{ username_on_the_host.stdout }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: ~/.ssh/id_rsa

    #- name: Read SSH public key to authorize
    #  shell: cat /home/foo/.ssh/id_rsa.pub
    #  register: ssh_pub_key

    #- name: Authorize key with GitHub
      #local_action:
        #module: github_key
        #name: Access Key for Some Machine
        #token: '{{ github_access_token }}'
        #pubkey: '{{ ssh_pub_key.stdout }}'
